# Configure how many times the channels list is reproduced
repetitions: 1

# Enable rebuffering logging (default is 0)
enableRebufferingTracing: 0

# Configuration for timings
timings:
  load: 5000  # milliseconds (5 seconds)
  play: 72000 # milliseconds (12 minutes)

# URL of the Content Provider
homepage: "https://www.primevideo.com/region/eu/livetv"

# Channels
channels:
  - type:      "url"
    link:      "https://www.primevideo.com/region/eu/detail/0FT3UFJI3UWL3FR9STND0K0SUG/ref=atv_hm_fcv_prime_hd_live_play_t1ACAAAAAA0wh0?autoplay=1&t=2147483647&type=live"
    name:      "eurosport1"

  # - type:      "url"
  #   link:      "https://www.primevideo.com/region/eu/detail/0FT3UFJI3UWL3FR9STND0K0SUG/ref=atv_hm_fcv_prime_hd_live_play_t1ACAAAAAA0wh0?autoplay=1&t=2147483647&type=live"
  #   name:      "eurosport2"

# Configuration for the sniffer
sniffer:
  bin: "/usr/bin/tshark"
  net: "enp1s0"
  max: "500"

# Configuration for sign-up
login:
  url: "https://www.primevideo.com/auth-redirect"
  username: ""
  password: ""
